name: UPDATE STAFF WIKI

on:
  push:
    paths:
      - 'Staff/wiki/**/*.md' # S'active uniquement pour les fichiers dans Staff/wiki
      - 'Staff/wiki/scan.py'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Clonage des données
        uses: actions/checkout@v4
        
      - name: ⚙️ Lancement du Cardinal Script
        run: python Staff/wiki/scan.py
        
      - name: 💾 Sauvegarde du nouveau Menu
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 [SYS] Auto-update Menu Navigation"
          file_pattern: Staff/wiki/_sidebar.md
